### ISSUE TITLE
MacOS Monterey and PHP

### ISSUE THREAD

**Issue by adamkiss** [adamkiss/alfred-kirby-search#10]
Document possible solutions for people who don't have the PHP available in the Bash CLI, as Monterey (macOS 12+) removed the builtin PHP.

**Comment by HYR** [comment]
I just upgraded to Monterey... bummed it stopped working. ☹️

**Comment by adamkiss** [comment]
I don't have access to Monterey computer, but it should be "fairly simple" to provide a working guide - you only need to have PHP accessible to CLI. Homebrew version, MAMP, etc. It's just not been priority so far

**Comment by HYR** [comment]
I have php installed via Homebrew. Running `which php` in the terminal tells me the path is `/usr/local/bin/php` which matches an option in Alfred 4...

<img width="787" alt="CleanShot 2022-01-17 at 16 32 49@2x" src="https://user-images.githubusercontent.com/5200901/149847620-815ba49b-e77e-4ef5-9cd7-104062a9d887.png">

No luck though. But when I open the Alfred workflow in the terminal and run it manually I do get data back: 

<img width="778" alt="CleanShot 2022-01-17 at 16 36 14@2x" src="https://user-images.githubusercontent.com/5200901/149847859-0684caff-c269-4de5-92ea-df1ea5c41294.png">

Here's the console from within the workflow: 

<img width="848" alt="CleanShot 2022-01-17 at 16 53 22@2x" src="https://user-images.githubusercontent.com/5200901/149848916-e8f6c6ff-c095-4d8d-a6d8-91ddfc915ef6.png">

**Comment by HYR** [comment]
Ok, changing the script to be `/usr/local/bin/php index.php "{query}"` fixes the issue for me with Homebrew.

<img width="792" alt="CleanShot 2022-01-17 at 17 26 17@2x" src="https://user-images.githubusercontent.com/5200901/149850843-c576ac3e-cdb4-4633-9fde-932bf0132a46.png">

Odd that the dropdown option with `/usr/local/bin/php` doesn't work. 🤷‍♂️

**Comment by adamkiss** [comment]
It is odd. It is also odd that your Homebrew installed PHP doesn't work as PHP. Do you not have your `/usr/local/bin` in the `$PATH`? I thought it was - so that you don't have to link every Homebrew application?

**Comment by adamkiss** [comment]
After _some_ testing, I figured out it actually didn't use the Homebrew PHP on my machine either 😓 After figuring out what to do, I actually ended up exporting to `$PATH`, the same way @foxacid did it in #9. I should probably document this in readme :D
