### ISSUE TITLE
Alfred 4.6

### ISSUE THREAD

**Issue by TakiKio** [adamkiss/alfred-kirby-search#9]
Kirby Docs search is not working under Alfred 4.6. 
![Bildschirmfoto 2021-12-06 um 14 20 20](https://user-images.githubusercontent.com/15986341/144853227-255b4313-3ee5-4fb6-9354-cd73aef78c51.png)

**Comment by adamkiss** [comment]
@TakiKio I am afraid I'll need more than that - works fine for me, running on 4.6.1

**Comment by foxacid** [comment]
Unfortunately it's not working anymore for me either. Possibly due to Monterey upgrade?

Mac OS 12.0.1 (M1)
Alfred 4.6.1

https://user-images.githubusercontent.com/12812201/145106702-48d60fcb-3448-48a9-b998-0ecb775b508d.mov

**Comment by adamkiss** [comment]
@foxacid huh, Monterey - that’s probably it. Monterey removed the system wide PHP, and this script is a PHP script run from cli. Could that be it?

**Comment by foxacid** [comment]
ah, yes. that must be it: https://www.alfredforum.com/topic/17062-using-php-on-monterey-macos-12

**Comment by foxacid** [comment]
tbh that's all slightly over my head. I'm not sure what's the best way to proceed here. I'm using MAMP PRO's PHP. Should I additionally install PHP via Homebrew and link that up?

**Comment by foxacid** [comment]
OK I got it up and running. I installed PHP via Homebrew and added the path before the script ([hint](https://www.alfredforum.com/topic/17062-using-php-on-monterey-macos-12/?do=findComment&comment=90246)), like so:

![image](https://user-images.githubusercontent.com/12812201/145115267-6cde1696-41b4-4cab-bde5-ed4d4334e10d.png)

**Comment by foxacid** [comment]
OK, next problem is that `{query}` seems to be passed as a string!?

![image](https://user-images.githubusercontent.com/12812201/145115917-2cb0e2ba-b821-41fb-a88b-17ae0289882d.png)

**Comment by foxacid** [comment]
🥳 back in the game with the generous help of @adamkiss and script setting `with input as {query}`

![Screen Shot 2021-12-08 at 23 08 39](https://user-images.githubusercontent.com/12812201/145292580-99f2dae3-2fef-4ff3-8bc9-3d05fe5d679d.png)

**Comment by TakiKio** [comment]
export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"

Thank you, that does the trick!

**Comment by adamkiss** [comment]
Ok, so it's definitely Monterey / PHP issue, not an Alfred 4.6 issue. I'll make a new issue with a description, closing this one.
